spring.application.name=cafeteria-server
server.port=8080

spring.datasource.url=jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/cafeteria_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=${DATABASE_USER:root}
spring.datasource.password=${DATABASE_PASSWORD:marte}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
